init for Android O
Signed-off-by: Deep Lee <deeplee0370@gmail.com>

diff --git a/util/init_script b/util/init_script
--- a/util/init_script
+++ b/util/init_script
@@ -8,7 +8,7 @@
 # Default-Stop:
 # Short-Description: Start and stop fuse.
 # Description:       Load the fuse module and mount the fuse control
-#	filesystem.
+#    filesystem.
 ### END INIT INFO
 
 set -e
@@ -21,69 +21,69 @@ which fusermount &>/dev/null || exit 5
 
 case "$1" in
     start|restart|force-reload)
-	if ! grep -qw fuse /proc/filesystems; then
-		echo -n "Loading fuse module"
-		if ! modprobe fuse >/dev/null 2>&1; then
-			echo " failed!"
-			exit 1
-		else
-			echo "."
-		fi
-	else
-		echo "Fuse filesystem already available."
-	fi
-	if grep -qw fusectl /proc/filesystems && \
-	   ! grep -qw $MOUNTPOINT /proc/mounts; then
-		echo -n "Mounting fuse control filesystem"
-		if ! mount -t fusectl fusectl $MOUNTPOINT >/dev/null 2>&1; then
-			echo " failed!"
-			exit 1
-		else
-			echo "."
-		fi
-	else
-		echo "Fuse control filesystem already available."
-	fi
-	;;
+    if ! grep -qw fuse /proc/filesystems; then
+        echo -n "Loading fuse module"
+        if ! modprobe fuse >/dev/null 2>&1; then
+            echo " failed!"
+            exit 1
+        else
+            echo "."
+        fi
+    else
+        echo "Fuse filesystem already available."
+    fi
+    if grep -qw fusectl /proc/filesystems && \
+       ! grep -qw $MOUNTPOINT /proc/mounts; then
+        echo -n "Mounting fuse control filesystem"
+        if ! mount -t fusectl fusectl $MOUNTPOINT >/dev/null 2>&1; then
+            echo " failed!"
+            exit 1
+        else
+            echo "."
+        fi
+    else
+        echo "Fuse control filesystem already available."
+    fi
+    ;;
     stop)
-	if ! grep -qw fuse /proc/filesystems; then
-		echo "Fuse filesystem not loaded."
-		exit 7
-	fi
-	if grep -qw $MOUNTPOINT /proc/mounts; then
-		echo -n "Unmounting fuse control filesystem"
-		if ! umount $MOUNTPOINT >/dev/null 2>&1; then
-			echo " failed!"
-		else
-			echo "."
-		fi
-	else
-		echo "Fuse control filesystem not mounted."
-	fi
-	if grep -qw "^fuse" /proc/modules; then
-		echo -n "Unloading fuse module"
-		if ! rmmod fuse >/dev/null 2>&1; then
-			echo " failed!"
-		else
-			echo "."
-		fi
-	else
-		echo "Fuse module not loaded."
-	fi
-	;;
+    if ! grep -qw fuse /proc/filesystems; then
+        echo "Fuse filesystem not loaded."
+        exit 7
+    fi
+    if grep -qw $MOUNTPOINT /proc/mounts; then
+        echo -n "Unmounting fuse control filesystem"
+        if ! umount $MOUNTPOINT >/dev/null 2>&1; then
+            echo " failed!"
+        else
+            echo "."
+        fi
+    else
+        echo "Fuse control filesystem not mounted."
+    fi
+    if grep -qw "^fuse" /proc/modules; then
+        echo -n "Unloading fuse module"
+        if ! rmmod fuse >/dev/null 2>&1; then
+            echo " failed!"
+        else
+            echo "."
+        fi
+    else
+        echo "Fuse module not loaded."
+    fi
+    ;;
     status)
-	echo -n "Checking fuse filesystem"
-	if ! grep -qw fuse /proc/filesystems; then
-		echo " not available."
-		exit 3
-	else
-		echo " ok."
-	fi
-	;;
+    echo -n "Checking fuse filesystem"
+    if ! grep -qw fuse /proc/filesystems; then
+        echo " not available."
+        exit 3
+    else
+        echo " ok."
+    fi
+    ;;
   *)
-	echo "Usage: $0 {start|stop|restart|force-reload|status}"
-	exit 1
-	;;
+    echo "Usage: $0 {start|stop|restart|force-reload|status}"
+    exit 1
+    ;;
 esac
 
 exit 0
